# Default values for kube-dump.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

cronSchedule: "0 0 * * *" # Example schedule, adjust as needed

# Controls kube-dump options.
dump:
  type: "all" # all / ns / cls (all / namespaced objects / cluster objects) [default: all]
  namespaces: # [ "kube-system", "cilium" ] # List of namespaces to dump, empty list (default) means all namespaces; only applies when type is "all" or "ns"
  encrypt: # list of "age" recipients to encrypt the dump with; up to nine can be specified; if none, dump is not encrypted. if more than one specified, any of them can decrypt.
    recipients: # [ "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDJhuKnM2yPGoj//d6CW2hZKuAilBpXYHNb1Xm2pajpW someone@candecrypt.net" ]
  output:
    nfs:
      enabled: false
      #server: "192.168.66.97"
      #path: "/mnt/adhoc/kube-dump/vmtest"
  rotate: 
    enabled: false # passes "--archive-rotate-days keep" to kube-dump
    keep: 30 # Number of _days_ to keep old backups in NFS. This is used as find's -mtime "+keep" option. To match "1", a file has to have been modified at least two days ago.

# This sets the container image more information can be found here: https://kubernetes.io/docs/concepts/containers/images/
image:
  repository: "ghcr.io/k8s-avengers/kube-dump" # set by GHA at Wed Apr  9 03:35:38 UTC 2025
  # This sets the pull policy for images.
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

# This is for the secretes for pulling an image from a private repository more information can be found here: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: [ ]
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

# This section builds out the service account more information can be found here: https://kubernetes.io/docs/concepts/security/service-accounts/
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# This is for setting Kubernetes Annotations to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
podAnnotations: { }
# This is for setting Kubernetes Labels to a Pod.
# For more information checkout: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
podLabels: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

resources: { }
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: [ ]
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: [ ]
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: { }

tolerations: [ ]

affinity: { }
