{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-dump.serviceAccountName" . }}
  labels:
    {{- include "kube-dump.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
# ClusterRole that can get/list/read all resources in all api groups
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube-dump.clusterRoleName" . }}
  labels:
    {{- include "kube-dump.labels" . | nindent 4 }}
rules:
  - verbs: [ "get", "list" ]
    apiGroups: [ "*" ]
    resources: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-dump.clusterRoleBindingName" . }}
  labels:
    {{- include "kube-dump.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-dump.clusterRoleName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kube-dump.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
